import * as stylex from "@stylexjs/stylex";
import { consts } from "../styles/consts.stylex";
import { fileFolder, fileMenuItem, fileRow, fileTree } from "../styles/markers.stylex";
import { tokens } from "../styles/tokens.stylex";

const COARSE = "@media (pointer: coarse)";
const ENDING = ":is([data-starting-style], [data-ending-style])";
const fade = {
  transitionDuration: { default: "120ms", [consts.reduceMotion]: "0s" },
  transitionTimingFunction: "ease-out",
} as const;
const focusRing = {
  outlineWidth: 2,
  outlineStyle: { default: "none", ":focus-visible": "solid" },
  outlineColor: tokens.ring,
  outlineOffset: 2,
} as const;

export const styles = stylex.create({
  root: {
    position: "relative",
    fontSize: 13.5,
    lineHeight: 1.5,
    color: tokens.foreground,
    userSelect: "none",
    cursor: { default: null, ":is([data-dragging])": "grabbing" },
  },
  head: {
    display: "flex",
    alignItems: "center",
    padding: "0.25rem 0.25rem 0.25rem 0.75rem",
    color: tokens.mutedForeground,
    fontSize: 12,
    fontWeight: 500,
  },
  title: {
    minWidth: 0,
    flexGrow: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  list: { margin: 0, padding: 0, listStyle: "none" },
  row: {
    display: "flex",
    alignItems: "center",
    borderRadius: "0.5rem",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.accent,
      ":has([data-popup-open])": tokens.accent,
      ':has([aria-current="page"])': `color-mix(in oklab, ${tokens.primary} 10%, transparent)`,
      [stylex.when.ancestor("[data-dragging]", fileTree)]: "transparent",
    },
    opacity: { default: 1, ":is([data-lifted])": 0.4 },
  },
  item: {
    display: "flex",
    boxSizing: "border-box",
    minWidth: 0,
    flexGrow: 1,
    minHeight: { default: "2rem", [COARSE]: "2.5rem" },
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.375rem 0.625rem",
    paddingInlineStart: "calc(0.625rem + var(--depth) * 1rem)",
    borderWidth: 0,
    borderRadius: "0.5rem",
    backgroundColor: "transparent",
    color: {
      default: tokens.mutedForeground,
      [stylex.when.ancestor(":hover", fileRow)]: tokens.foreground,
      ':is([aria-current="page"])': tokens.primary,
    },
    font: "inherit",
    fontWeight: 500,
    textAlign: "start",
    textDecorationLine: "none",
    cursor: "pointer",
    ...focusRing,
  },
  folder: { color: tokens.foreground },
  separator: {
    minHeight: "1.75rem",
    marginTop: "0.5rem",
    paddingBlock: "0.25rem",
    paddingInlineStart: "calc(0.75rem + var(--depth) * 1rem)",
    fontSize: 12,
  },
  edit: { cursor: "text" },
  icon: { flexShrink: 0 },
  chevron: {
    flexShrink: 0,
    rotate: { default: "0deg", [stylex.when.ancestor("[data-panel-open]", fileFolder)]: "90deg" },
    transitionProperty: "rotate",
    transitionDuration: { default: "100ms", [consts.reduceMotion]: "0s" },
    transitionTimingFunction: "ease-out",
  },
  collapse: {
    height: { default: "var(--collapsible-panel-height)", [ENDING]: 0 },
    overflow: "hidden",
    transitionProperty: "height",
    ...fade,
  },
  label: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  control: {
    display: "inline-flex",
    boxSizing: "border-box",
    width: "1.5rem",
    height: "1.5rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
    borderRadius: "0.375rem",
    backgroundColor: "transparent",
    color: tokens.mutedForeground,
    font: "inherit",
    cursor: "pointer",
  },
  action: {
    marginInlineEnd: "0.25rem",
    opacity: {
      default: 0,
      [stylex.when.ancestor(":hover", fileRow)]: 1,
      [stylex.when.ancestor(":focus-within", fileRow)]: 1,
      ":is([data-popup-open])": 1,
      [COARSE]: 1,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in oklab, ${tokens.foreground} 10%, transparent)`,
      ":is([data-popup-open])": `color-mix(in oklab, ${tokens.foreground} 10%, transparent)`,
    },
    color: {
      default: tokens.mutedForeground,
      ":hover": tokens.foreground,
      ":is([data-popup-open])": tokens.foreground,
    },
    transitionProperty: "opacity",
    transitionDuration: "100ms",
    ...focusRing,
    outlineOffset: -2,
  },
  shown: { opacity: 1 },
  grip: {
    display: { default: "none", [COARSE]: "inline-flex" },
    cursor: "grab",
    touchAction: "none",
  },
  line: {
    position: "absolute",
    zIndex: 1,
    height: 2,
    borderRadius: 1,
    backgroundColor: tokens.primary,
    pointerEvents: "none",
  },
  input: {
    minWidth: 0,
    flexGrow: 1,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.foreground,
    font: "inherit",
    fontSize: `max(13.5px, ${tokens.fieldSize})`,
    outline: "none",
    "::placeholder": { color: tokens.mutedForeground, opacity: 0.7 },
  },
  hint: {
    overflow: "hidden",
    padding: "0 0.625rem 0.375rem",
    paddingInlineStart: "calc(2.0625rem + var(--depth) * 1rem)",
    color: tokens.mutedForeground,
    fontFamily: consts.mono,
    fontSize: 11,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  notice: {
    position: "sticky",
    bottom: 0,
    margin: "0.375rem 0 0",
    padding: "0.5rem 0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.border,
    borderRadius: "0.5rem",
    backgroundColor: tokens.popover,
    color: tokens.error,
    fontSize: 12,
    overflowWrap: "anywhere",
  },
  menu: {
    minWidth: "13.5rem",
    transformOrigin: "var(--transform-origin)",
    opacity: { default: 1, [ENDING]: 0 },
    scale: { default: "1", [ENDING]: "0.97" },
    transitionProperty: "opacity, scale",
    ...fade,
  },
  menuLabel: {
    overflow: "hidden",
    padding: "0.375rem 0.625rem 0.5rem",
    color: tokens.mutedForeground,
    fontFamily: consts.mono,
    fontSize: 11,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  menuSeparator: { height: 1, margin: "0.25rem -0.25rem", backgroundColor: tokens.border },
  menuItem: {
    minHeight: { default: "2rem", [COARSE]: "2.5rem" },
    gap: "0.625rem",
    paddingInline: "0.625rem",
    opacity: { default: 1, ":is([data-disabled])": 0.45 },
    outline: "none",
  },
  danger: {
    color: { default: tokens.error, ":is([data-highlighted])": tokens.error },
    backgroundColor: {
      default: "transparent",
      ":is([data-highlighted])": `color-mix(in oklab, ${tokens.error} 12%, transparent)`,
    },
  },
  menuIcon: {
    color: {
      default: tokens.mutedForeground,
      [stylex.when.ancestor("[data-danger]", fileMenuItem)]: tokens.error,
      [stylex.when.ancestor("[data-highlighted]", fileMenuItem)]: "inherit",
    },
  },
  menuText: { flexGrow: 1 },
  keys: {
    display: { default: null, [COARSE]: "none" },
    marginInlineStart: "1rem",
    color: {
      default: tokens.mutedForeground,
      [stylex.when.ancestor("[data-highlighted]", fileMenuItem)]: "inherit",
    },
    font: "inherit",
    fontSize: 11.5,
    letterSpacing: "0.02em",
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 60,
    backgroundColor: "rgb(0 0 0 / 0.3)",
    opacity: { default: 1, [ENDING]: 0 },
    transitionProperty: "opacity",
    ...fade,
  },
  viewport: {
    position: "fixed",
    inset: 0,
    zIndex: 61,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "1rem",
  },
  confirm: {
    width: "100%",
    maxWidth: "22rem",
    padding: "1.25rem",
    borderRadius: "0.875rem",
    opacity: { default: 1, [ENDING]: 0 },
    translate: { default: "0 0", [ENDING]: "0 0.5rem" },
    transitionProperty: "opacity, translate",
    ...fade,
  },
  confirmTitle: { margin: "0 0 0.5rem", fontSize: 15, fontWeight: 600 },
  confirmText: { margin: 0, color: tokens.mutedForeground, fontSize: 13, overflowWrap: "anywhere" },
  code: { fontFamily: consts.mono, fontSize: 12 },
  actions: { display: "flex", justifyContent: "flex-end", gap: "0.5rem", marginTop: "1.25rem" },
  button: {
    boxSizing: "border-box",
    height: "2rem",
    padding: "0 0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.border,
    borderRadius: "0.5rem",
    backgroundColor: { default: tokens.secondary, ":hover": tokens.accent },
    color: tokens.secondaryForeground,
    font: "inherit",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    ...focusRing,
  },
  dangerButton: {
    borderColor: tokens.error,
    backgroundColor: {
      default: tokens.error,
      ":hover": `color-mix(in oklab, ${tokens.error} 85%, black)`,
    },
    color: "#fff",
  },
});
